### ISSUE TITLE
Fix button

### ISSUE THREAD

**Issue by Jvr2022** [xanonDev/RestrictBypass#5]
The change darkmode button is working because the image is not found.
![image](https://github.com/xanonDev/RestrictBypass/assets/109031036/2dd7b591-f2e9-45dd-8e9c-4b26bac18bad)

I can create a image for changing. @xanonDev please review this issue

**Comment by Jvr2022** [comment]
maybe something like his 
![Removal-433](https://github.com/xanonDev/RestrictBypass/assets/109031036/502d88e5-c93c-42cb-8f9e-15a068481559)

**Comment by Jvr2022** [comment]
@wojtas3422 @xanonDev what do you guys think about this?

**Comment by wojtas3422** [comment]
fix it?

download dark and light mode from material icons

**Comment by Jvr2022** [comment]
I dont like google material icons @wojtas3422

**Comment by xanonDev** [comment]
i fix that @Jvr2022 check Is it working

**Comment by Jvr2022** [comment]
@xanonDev since the new commits google says on my phone that its a dangerous site

**Comment by Jvr2022** [comment]
that cybercriminals try to steal my data

**Comment by Jvr2022** [comment]
but i know that it is not true

**Comment by xanonDev** [comment]
I saw this and i write revocation
